/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YouIndexRouteImport } from './routes/you/index'
import { Route as WorkstreamsIndexRouteImport } from './routes/workstreams/index'
import { Route as UnlockIndexRouteImport } from './routes/unlock/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RitualsIndexRouteImport } from './routes/rituals/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as NodesIndexRouteImport } from './routes/nodes/index'
import { Route as MemoriesIndexRouteImport } from './routes/memories/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as GoalsIndexRouteImport } from './routes/goals/index'
import { Route as FilesystemIndexRouteImport } from './routes/filesystem/index'
import { Route as DebugIndexRouteImport } from './routes/debug/index'
import { Route as ConversationsIndexRouteImport } from './routes/conversations/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentStatusIndexRouteImport } from './routes/agent-status/index'
import { Route as WorkstreamsWorkstreamIdRouteImport } from './routes/workstreams/$workstreamId'
import { Route as DebugWorkbenchRouteImport } from './routes/debug/workbench'
import { Route as DebugTerminalRouteImport } from './routes/debug/terminal'
import { Route as DebugGraphRouteImport } from './routes/debug/graph'
import { Route as ConversationsIdRouteImport } from './routes/conversations/$id'
import { Route as AgentsNewRouteImport } from './routes/agents/new'
import { Route as AgentsGraphRouteImport } from './routes/agents/graph'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as ConversationsIdAgenticRouteImport } from './routes/conversations/$id/agentic'
import { Route as AgentsAgentIdConfigureRouteImport } from './routes/agents/$agentId/configure'
import { Route as AgentsAgentIdSessionIndexRouteImport } from './routes/agents/$agentId/session/index'
import { Route as AgentsAgentIdSessionSessionKeyRouteImport } from './routes/agents/$agentId/session/$sessionKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YouIndexRoute = YouIndexRouteImport.update({
  id: '/you/',
  path: '/you/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkstreamsIndexRoute = WorkstreamsIndexRouteImport.update({
  id: '/workstreams/',
  path: '/workstreams/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockIndexRoute = UnlockIndexRouteImport.update({
  id: '/unlock/',
  path: '/unlock/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualsIndexRoute = RitualsIndexRouteImport.update({
  id: '/rituals/',
  path: '/rituals/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesystemIndexRoute = FilesystemIndexRouteImport.update({
  id: '/filesystem/',
  path: '/filesystem/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugIndexRoute = DebugIndexRouteImport.update({
  id: '/debug/',
  path: '/debug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIndexRoute = ConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentStatusIndexRoute = AgentStatusIndexRouteImport.update({
  id: '/agent-status/',
  path: '/agent-status/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkstreamsWorkstreamIdRoute = WorkstreamsWorkstreamIdRouteImport.update({
  id: '/workstreams/$workstreamId',
  path: '/workstreams/$workstreamId',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugWorkbenchRoute = DebugWorkbenchRouteImport.update({
  id: '/debug/workbench',
  path: '/debug/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugTerminalRoute = DebugTerminalRouteImport.update({
  id: '/debug/terminal',
  path: '/debug/terminal',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/debug/terminal.lazy').then((d) => d.Route),
)
const DebugGraphRoute = DebugGraphRouteImport.update({
  id: '/debug/graph',
  path: '/debug/graph',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/debug/graph.lazy').then((d) => d.Route))
const ConversationsIdRoute = ConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/agents/new.lazy').then((d) => d.Route))
const AgentsGraphRoute = AgentsGraphRouteImport.update({
  id: '/agents/graph',
  path: '/agents/graph',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/agents/graph.lazy').then((d) => d.Route))
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIdAgenticRoute = ConversationsIdAgenticRouteImport.update({
  id: '/agentic',
  path: '/agentic',
  getParentRoute: () => ConversationsIdRoute,
} as any)
const AgentsAgentIdConfigureRoute = AgentsAgentIdConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdSessionIndexRoute =
  AgentsAgentIdSessionIndexRouteImport.update({
    id: '/session/',
    path: '/session/',
    getParentRoute: () => AgentsAgentIdRoute,
  } as any)
const AgentsAgentIdSessionSessionKeyRoute =
  AgentsAgentIdSessionSessionKeyRouteImport.update({
    id: '/session/$sessionKey',
    path: '/session/$sessionKey',
    getParentRoute: () => AgentsAgentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/graph': typeof AgentsGraphRoute
  '/agents/new': typeof AgentsNewRoute
  '/conversations/$id': typeof ConversationsIdRouteWithChildren
  '/debug/graph': typeof DebugGraphRoute
  '/debug/terminal': typeof DebugTerminalRoute
  '/debug/workbench': typeof DebugWorkbenchRoute
  '/workstreams/$workstreamId': typeof WorkstreamsWorkstreamIdRoute
  '/agent-status/': typeof AgentStatusIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/conversations/': typeof ConversationsIndexRoute
  '/debug/': typeof DebugIndexRoute
  '/filesystem/': typeof FilesystemIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/memories/': typeof MemoriesIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/rituals/': typeof RitualsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/unlock/': typeof UnlockIndexRoute
  '/workstreams/': typeof WorkstreamsIndexRoute
  '/you/': typeof YouIndexRoute
  '/agents/$agentId/configure': typeof AgentsAgentIdConfigureRoute
  '/conversations/$id/agentic': typeof ConversationsIdAgenticRoute
  '/agents/$agentId/session/$sessionKey': typeof AgentsAgentIdSessionSessionKeyRoute
  '/agents/$agentId/session/': typeof AgentsAgentIdSessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/graph': typeof AgentsGraphRoute
  '/agents/new': typeof AgentsNewRoute
  '/conversations/$id': typeof ConversationsIdRouteWithChildren
  '/debug/graph': typeof DebugGraphRoute
  '/debug/terminal': typeof DebugTerminalRoute
  '/debug/workbench': typeof DebugWorkbenchRoute
  '/workstreams/$workstreamId': typeof WorkstreamsWorkstreamIdRoute
  '/agent-status': typeof AgentStatusIndexRoute
  '/agents': typeof AgentsIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/conversations': typeof ConversationsIndexRoute
  '/debug': typeof DebugIndexRoute
  '/filesystem': typeof FilesystemIndexRoute
  '/goals': typeof GoalsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/logs': typeof LogsIndexRoute
  '/memories': typeof MemoriesIndexRoute
  '/nodes': typeof NodesIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/rituals': typeof RitualsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/unlock': typeof UnlockIndexRoute
  '/workstreams': typeof WorkstreamsIndexRoute
  '/you': typeof YouIndexRoute
  '/agents/$agentId/configure': typeof AgentsAgentIdConfigureRoute
  '/conversations/$id/agentic': typeof ConversationsIdAgenticRoute
  '/agents/$agentId/session/$sessionKey': typeof AgentsAgentIdSessionSessionKeyRoute
  '/agents/$agentId/session': typeof AgentsAgentIdSessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/graph': typeof AgentsGraphRoute
  '/agents/new': typeof AgentsNewRoute
  '/conversations/$id': typeof ConversationsIdRouteWithChildren
  '/debug/graph': typeof DebugGraphRoute
  '/debug/terminal': typeof DebugTerminalRoute
  '/debug/workbench': typeof DebugWorkbenchRoute
  '/workstreams/$workstreamId': typeof WorkstreamsWorkstreamIdRoute
  '/agent-status/': typeof AgentStatusIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/conversations/': typeof ConversationsIndexRoute
  '/debug/': typeof DebugIndexRoute
  '/filesystem/': typeof FilesystemIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/memories/': typeof MemoriesIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/rituals/': typeof RitualsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/unlock/': typeof UnlockIndexRoute
  '/workstreams/': typeof WorkstreamsIndexRoute
  '/you/': typeof YouIndexRoute
  '/agents/$agentId/configure': typeof AgentsAgentIdConfigureRoute
  '/conversations/$id/agentic': typeof ConversationsIdAgenticRoute
  '/agents/$agentId/session/$sessionKey': typeof AgentsAgentIdSessionSessionKeyRoute
  '/agents/$agentId/session/': typeof AgentsAgentIdSessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents/$agentId'
    | '/agents/graph'
    | '/agents/new'
    | '/conversations/$id'
    | '/debug/graph'
    | '/debug/terminal'
    | '/debug/workbench'
    | '/workstreams/$workstreamId'
    | '/agent-status/'
    | '/agents/'
    | '/analytics/'
    | '/conversations/'
    | '/debug/'
    | '/filesystem/'
    | '/goals/'
    | '/jobs/'
    | '/logs/'
    | '/memories/'
    | '/nodes/'
    | '/onboarding/'
    | '/rituals/'
    | '/settings/'
    | '/skills/'
    | '/unlock/'
    | '/workstreams/'
    | '/you/'
    | '/agents/$agentId/configure'
    | '/conversations/$id/agentic'
    | '/agents/$agentId/session/$sessionKey'
    | '/agents/$agentId/session/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/$agentId'
    | '/agents/graph'
    | '/agents/new'
    | '/conversations/$id'
    | '/debug/graph'
    | '/debug/terminal'
    | '/debug/workbench'
    | '/workstreams/$workstreamId'
    | '/agent-status'
    | '/agents'
    | '/analytics'
    | '/conversations'
    | '/debug'
    | '/filesystem'
    | '/goals'
    | '/jobs'
    | '/logs'
    | '/memories'
    | '/nodes'
    | '/onboarding'
    | '/rituals'
    | '/settings'
    | '/skills'
    | '/unlock'
    | '/workstreams'
    | '/you'
    | '/agents/$agentId/configure'
    | '/conversations/$id/agentic'
    | '/agents/$agentId/session/$sessionKey'
    | '/agents/$agentId/session'
  id:
    | '__root__'
    | '/'
    | '/agents/$agentId'
    | '/agents/graph'
    | '/agents/new'
    | '/conversations/$id'
    | '/debug/graph'
    | '/debug/terminal'
    | '/debug/workbench'
    | '/workstreams/$workstreamId'
    | '/agent-status/'
    | '/agents/'
    | '/analytics/'
    | '/conversations/'
    | '/debug/'
    | '/filesystem/'
    | '/goals/'
    | '/jobs/'
    | '/logs/'
    | '/memories/'
    | '/nodes/'
    | '/onboarding/'
    | '/rituals/'
    | '/settings/'
    | '/skills/'
    | '/unlock/'
    | '/workstreams/'
    | '/you/'
    | '/agents/$agentId/configure'
    | '/conversations/$id/agentic'
    | '/agents/$agentId/session/$sessionKey'
    | '/agents/$agentId/session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRouteWithChildren
  AgentsGraphRoute: typeof AgentsGraphRoute
  AgentsNewRoute: typeof AgentsNewRoute
  ConversationsIdRoute: typeof ConversationsIdRouteWithChildren
  DebugGraphRoute: typeof DebugGraphRoute
  DebugTerminalRoute: typeof DebugTerminalRoute
  DebugWorkbenchRoute: typeof DebugWorkbenchRoute
  WorkstreamsWorkstreamIdRoute: typeof WorkstreamsWorkstreamIdRoute
  AgentStatusIndexRoute: typeof AgentStatusIndexRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  ConversationsIndexRoute: typeof ConversationsIndexRoute
  DebugIndexRoute: typeof DebugIndexRoute
  FilesystemIndexRoute: typeof FilesystemIndexRoute
  GoalsIndexRoute: typeof GoalsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
  NodesIndexRoute: typeof NodesIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  RitualsIndexRoute: typeof RitualsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  UnlockIndexRoute: typeof UnlockIndexRoute
  WorkstreamsIndexRoute: typeof WorkstreamsIndexRoute
  YouIndexRoute: typeof YouIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you/': {
      id: '/you/'
      path: '/you'
      fullPath: '/you/'
      preLoaderRoute: typeof YouIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workstreams/': {
      id: '/workstreams/'
      path: '/workstreams'
      fullPath: '/workstreams/'
      preLoaderRoute: typeof WorkstreamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock/': {
      id: '/unlock/'
      path: '/unlock'
      fullPath: '/unlock/'
      preLoaderRoute: typeof UnlockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rituals/': {
      id: '/rituals/'
      path: '/rituals'
      fullPath: '/rituals/'
      preLoaderRoute: typeof RitualsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/': {
      id: '/memories/'
      path: '/memories'
      fullPath: '/memories/'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/': {
      id: '/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filesystem/': {
      id: '/filesystem/'
      path: '/filesystem'
      fullPath: '/filesystem/'
      preLoaderRoute: typeof FilesystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/': {
      id: '/debug/'
      path: '/debug'
      fullPath: '/debug/'
      preLoaderRoute: typeof DebugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/': {
      id: '/conversations/'
      path: '/conversations'
      fullPath: '/conversations/'
      preLoaderRoute: typeof ConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-status/': {
      id: '/agent-status/'
      path: '/agent-status'
      fullPath: '/agent-status/'
      preLoaderRoute: typeof AgentStatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workstreams/$workstreamId': {
      id: '/workstreams/$workstreamId'
      path: '/workstreams/$workstreamId'
      fullPath: '/workstreams/$workstreamId'
      preLoaderRoute: typeof WorkstreamsWorkstreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/workbench': {
      id: '/debug/workbench'
      path: '/debug/workbench'
      fullPath: '/debug/workbench'
      preLoaderRoute: typeof DebugWorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/terminal': {
      id: '/debug/terminal'
      path: '/debug/terminal'
      fullPath: '/debug/terminal'
      preLoaderRoute: typeof DebugTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/graph': {
      id: '/debug/graph'
      path: '/debug/graph'
      fullPath: '/debug/graph'
      preLoaderRoute: typeof DebugGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$id': {
      id: '/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof ConversationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/graph': {
      id: '/agents/graph'
      path: '/agents/graph'
      fullPath: '/agents/graph'
      preLoaderRoute: typeof AgentsGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$id/agentic': {
      id: '/conversations/$id/agentic'
      path: '/agentic'
      fullPath: '/conversations/$id/agentic'
      preLoaderRoute: typeof ConversationsIdAgenticRouteImport
      parentRoute: typeof ConversationsIdRoute
    }
    '/agents/$agentId/configure': {
      id: '/agents/$agentId/configure'
      path: '/configure'
      fullPath: '/agents/$agentId/configure'
      preLoaderRoute: typeof AgentsAgentIdConfigureRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/session/': {
      id: '/agents/$agentId/session/'
      path: '/session'
      fullPath: '/agents/$agentId/session/'
      preLoaderRoute: typeof AgentsAgentIdSessionIndexRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/session/$sessionKey': {
      id: '/agents/$agentId/session/$sessionKey'
      path: '/session/$sessionKey'
      fullPath: '/agents/$agentId/session/$sessionKey'
      preLoaderRoute: typeof AgentsAgentIdSessionSessionKeyRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
  }
}

interface AgentsAgentIdRouteChildren {
  AgentsAgentIdConfigureRoute: typeof AgentsAgentIdConfigureRoute
  AgentsAgentIdSessionSessionKeyRoute: typeof AgentsAgentIdSessionSessionKeyRoute
  AgentsAgentIdSessionIndexRoute: typeof AgentsAgentIdSessionIndexRoute
}

const AgentsAgentIdRouteChildren: AgentsAgentIdRouteChildren = {
  AgentsAgentIdConfigureRoute: AgentsAgentIdConfigureRoute,
  AgentsAgentIdSessionSessionKeyRoute: AgentsAgentIdSessionSessionKeyRoute,
  AgentsAgentIdSessionIndexRoute: AgentsAgentIdSessionIndexRoute,
}

const AgentsAgentIdRouteWithChildren = AgentsAgentIdRoute._addFileChildren(
  AgentsAgentIdRouteChildren,
)

interface ConversationsIdRouteChildren {
  ConversationsIdAgenticRoute: typeof ConversationsIdAgenticRoute
}

const ConversationsIdRouteChildren: ConversationsIdRouteChildren = {
  ConversationsIdAgenticRoute: ConversationsIdAgenticRoute,
}

const ConversationsIdRouteWithChildren = ConversationsIdRoute._addFileChildren(
  ConversationsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsAgentIdRoute: AgentsAgentIdRouteWithChildren,
  AgentsGraphRoute: AgentsGraphRoute,
  AgentsNewRoute: AgentsNewRoute,
  ConversationsIdRoute: ConversationsIdRouteWithChildren,
  DebugGraphRoute: DebugGraphRoute,
  DebugTerminalRoute: DebugTerminalRoute,
  DebugWorkbenchRoute: DebugWorkbenchRoute,
  WorkstreamsWorkstreamIdRoute: WorkstreamsWorkstreamIdRoute,
  AgentStatusIndexRoute: AgentStatusIndexRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  ConversationsIndexRoute: ConversationsIndexRoute,
  DebugIndexRoute: DebugIndexRoute,
  FilesystemIndexRoute: FilesystemIndexRoute,
  GoalsIndexRoute: GoalsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
  NodesIndexRoute: NodesIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  RitualsIndexRoute: RitualsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  UnlockIndexRoute: UnlockIndexRoute,
  WorkstreamsIndexRoute: WorkstreamsIndexRoute,
  YouIndexRoute: YouIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
