export type Severity = "critical" | "high" | "medium" | "low";
export type Wave = 1 | 2 | 3;

export interface Finding {
  id: string;
  agentName: string;
  agentId: string;
  domain: string;
  wave: Wave;
  severity: Severity;
  title: string;
  excerpt: string;
  content: string;
  timestamp: string;
  tags: string[];
}

// 20 mock findings covering various domains, severities, and waves
export const FINDINGS: Finding[] = [
  {
    id: "f1",
    agentName: "SecurityScanner",
    agentId: "sec-001",
    domain: "Authentication",
    wave: 1,
    severity: "critical",
    title: "SQL Injection Vulnerability in Login Endpoint",
    excerpt: "The login endpoint /api/auth/login does not properly sanitize user input, allowing SQL injection attacks through the username parameter.",
    content: `## SQL Injection Vulnerability in Login Endpoint\n\n### Severity: Critical\n### Wave: 1\n\nThe login endpoint \`/api/auth/login\` does not properly sanitize user input, allowing SQL injection attacks through the username parameter.\n\n### Evidence\n\`\`\`sql\n' OR '1'='1' --\n\`\`\`\n\nThis payload successfully authenticates as any user without knowing the password.\n\n### Recommendation\n- Use parameterized queries (prepared statements)\n- Implement input validation and sanitization\n- Apply least privilege to database users\n- Add WAF rules for SQL injection patterns\n\n### CVSS Score: 9.8 (Critical)`,
    timestamp: "2026-02-15T14:32:00Z",
    tags: ["injection", "authentication", "owasp-top-10"],
  },
  {
    id: "f2",
    agentName: "PerformancePro",
    agentId: "perf-001",
    domain: "Performance",
    wave: 1,
    severity: "high",
    title: "N+1 Query Problem in Dashboard Loader",
    excerpt: "The dashboard data loader executes individual database queries for each widget, resulting in 47 queries for a standard dashboard view.",
    content: `## N+1 Query Problem in Dashboard Loader\n\n### Severity: High\n### Wave: 1\n\nThe dashboard data loader executes individual database queries for each widget, resulting in 47 queries for a standard dashboard view.\n\n### Impact\n- Average response time: 2.3s (target: <500ms)\n- Database CPU utilization: 85% during peak hours\n- Connection pool exhaustion under load\n\n### Root Cause\n\`\`\`javascript\n// Current implementation\nwidgets.forEach(widget => {\n  const data = await db.query(widget.dataQuery);\n  widget.data = data;\n});\n\`\`\`\n\n### Recommendation\n- Implement batched queries using IN clauses\n- Use DataLoader for batching and caching\n- Consider pre-aggregating dashboard data`,
    timestamp: "2026-02-14T09:15:00Z",
    tags: ["performance", "database", "optimization"],
  },
  {
    id: "f3",
    agentName: "A11yAudit",
    agentId: "a11y-001",
    domain: "Accessibility",
    wave: 1,
    severity: "medium",
    title: "Missing ARIA Labels on Navigation Icons",
    excerpt: "17 navigation icons lack proper ARIA labels, making the navigation unusable for screen reader users.",
    content: `## Missing ARIA Labels on Navigation Icons\n\n### Severity: Medium\n### Wave: 1\n\n17 navigation icons lack proper ARIA labels, making the navigation unusable for screen reader users.\n\n### Affected Elements\n- Home icon\n- Settings icon\n- Profile icon\n- Notifications icon\n- Search icon\n\n### WCAG Violation\n- WCAG 4.1.2: Name, Role, Value\n- Impact: Users cannot understand the purpose of icon-only buttons\n\n### Recommendation\nAdd \`aria-label\` to each icon button:\n\n\`\`\`jsx\n<button aria-label="Go to Home">\n  <HomeIcon />\n</button>\n\`\`\``,
    timestamp: "2026-02-13T16:45:00Z",
    tags: ["accessibility", "wcag", "screen-reader"],
  },
  {
    id: "f4",
    agentName: "SecurityScanner",
    agentId: "sec-001",
    domain: "API Security",
    wave: 2,
    severity: "critical",
    title: "Exposed API Keys in Client-Side Code",
    excerpt: "Stripe API secret key found embedded in JavaScript bundle. Publicly accessible through browser dev tools.",
    content: `## Exposed API Keys in Client-Side Code\n\n### Severity: Critical\n### Wave: 2\n\nStripe API secret key found embedded in JavaScript bundle. Publicly accessible through browser dev tools.\n\n### Discovery\n\`\`\`javascript\n// Found in main.js:15432\nconst STRIPE_SECRET = 'sk_live_51MzQ...';\n\`\`\`\n\n### Impact\n- Full access to Stripe account\n- Ability to process arbitrary charges\n- PCI DSS compliance violation\n\n### Immediate Actions\n1. Rotate exposed API key\n2. Implement server-side Stripe integration\n3. Add key rotation to security procedures\n4. Scan for other exposed secrets`,
    timestamp: "2026-02-18T11:20:00Z",
    tags: ["secrets", "api-keys", "compliance"],
  },
  {
    id: "f5",
    agentName: "UXAnalyzer",
    agentId: "ux-001",
    domain: "User Experience",
    wave: 2,
    severity: "low",
    title: "Inconsistent Button Styles in Admin Panel",
    excerpt: "Primary action buttons use different visual styles across admin panel pages, creating visual inconsistency.",
    content: `## Inconsistent Button Styles in Admin Panel\n\n### Severity: Low\n### Wave: 2\n\nPrimary action buttons use different visual styles across admin panel pages, creating visual inconsistency.\n\n### Findings\n- Page 1: Blue rounded buttons\n- Page 2: Gray square buttons\n- Page 3: Green outlined buttons\n\n### Impact\n- Minor confusion for power users\n- Perception of incomplete design system\n\n### Recommendation\nCreate a shared Button component with documented variants.`,
    timestamp: "2026-02-17T14:00:00Z",
    tags: ["ui", "consistency", "design-system"],
  },
  {
    id: "f6",
    agentName: "PerformancePro",
    agentId: "perf-001",
    domain: "Performance",
    wave: 2,
    severity: "high",
    title: "Missing Cache Headers on Static Assets",
    excerpt: "Static JavaScript and CSS files served without cache headers, causing unnecessary re-downloads on repeat visits.",
    content: `## Missing Cache Headers on Static Assets\n\n### Severity: High\n### Wave: 2\n\nStatic JavaScript and CSS files served without cache headers, causing unnecessary re-downloads on repeat visits.\n\n### Impact\n- 340KB redundant downloads per page load\n- 2.1s added to Time to Interactive on return visits\n- Increased bandwidth costs\n\n### Current Headers\n\`\`\`\nCache-Control: no-cache\n\`\`\`\n\n### Recommended Headers\n\`\`\`\nCache-Control: public, max-age=31536000, immutable\nETag: <generated-hash>\n\`\`\``,
    timestamp: "2026-02-16T10:30:00Z",
    tags: ["caching", "performance", "cdn"],
  },
  {
    id: "f7",
    agentName: "A11yAudit",
    agentId: "a11y-001",
    domain: "Accessibility",
    wave: 2,
    severity: "high",
    title: "Form Validation Errors Not Announced to Screen Readers",
    excerpt: "When form validation fails, error messages appear visually but are not announced to screen reader users.",
    content: `## Form Validation Errors Not Announced to Screen Readers\n\n### Severity: High\n### Wave: 2\n\nWhen form validation fails, error messages appear visually but are not announced to screen reader users.\n\n### WCAG Violations\n- WCAG 3.3.1: Error Identification\n- WCAG 4.1.3: Status Messages\n\n### Root Cause\n- Error messages use \`role="alert"\` but not consistently\n- Some errors only update visual text without ARIA announcements\n\n### Recommendation\n\`\`\`jsx\n<div role="alert" aria-live="polite">\n  {errorMessage}\n</div>\n\`\`\``,
    timestamp: "2026-02-15T08:45:00Z",
    tags: ["accessibility", "forms", "aria"],
  },
  {
    id: "f8",
    agentName: "SecurityScanner",
    agentId: "sec-001",
    domain: "Data Protection",
    wave: 3,
    severity: "critical",
    title: "PII Data Stored in Plain Text",
    excerpt: "User email addresses and phone numbers stored without encryption in the database, violating GDPR requirements.",
    content: `## PII Data Stored in Plain Text\n\n### Severity: Critical\n### Wave: 3\n\nUser email addresses and phone numbers stored without encryption in the database, violating GDPR requirements.\n\n### Discovery\n\`\`\`sql\nSELECT email, phone FROM users LIMIT 5;\n-- Returns plaintext PII\n\`\`\`\n\n### Compliance Impact\n- GDPR Article 32 violation\n- Potential data breach liability\n- Regulatory fines up to 4% of annual revenue\n\n### Required Actions\n1. Implement field-level encryption for PII\n2. Add encryption key rotation\n3. Audit all PII data flows\n4. Update data retention policies`,
    timestamp: "2026-02-20T13:00:00Z",
    tags: ["pii", "gdpr", "encryption"],
  },
  {
    id: "f9",
    agentName: "UXAnalyzer",
    agentId: "ux-001",
    domain: "User Experience",
    wave: 3,
    severity: "medium",
    title: "Checkout Flow Abandonment Due to Form Length",
    excerpt: "Checkout form has 14 required fields, causing 23% abandonment rate at the first step.",
    content: `## Checkout Flow Abandonment Due to Form Length\n\n### Severity: Medium\n### Wave: 3\n\nCheckout form has 14 required fields, causing 23% abandonment rate at the first step.\n\n### Analytics\n- Step 1 completion: 77%\n- Step 2 completion: 61%\n- Step 3 completion: 54%\n\n### Benchmark\nIndustry average: 8-10 fields\nTop performers: 5-7 fields\n\n### Recommendation\n- Make optional fields optional\n- Use address auto-complete\n- Enable account creation post-purchase\n- Single-page checkout for returning users`,
    timestamp: "2026-02-19T15:30:00Z",
    tags: ["conversion", "forms", "checkout"],
  },
  {
    id: "f10",
    agentName: "PerformancePro",
    agentId: "perf-001",
    domain: "Performance",
    wave: 3,
    severity: "medium",
    title: "Large Image Assets Not Optimized",
    excerpt: "Product images average 2.3MB each, causing slow page loads on mobile devices (LCP: 4.7s).",
    content: `## Large Image Assets Not Optimized\n\n### Severity: Medium\n### Wave: 3\n\nProduct images average 2.3MB each, causing slow page loads on mobile devices (LCP: 4.7s).\n\n### Metrics\n- Average image size: 2.3MB\n- Target: <200KB per image\n- LCP: 4.7s (target: <2.5s)\n\n### Recommendations\n1. Implement responsive images with srcset\n2. Use WebP/AVIF formats\n3. Add lazy loading below fold\n4. Consider image CDN`,
    timestamp: "2026-02-18T09:00:00Z",
    tags: ["images", "optimization", "mobile"],
  },
  {
    id: "f11",
    agentName: "SecurityScanner",
    agentId: "sec-001",
    domain: "Authentication",
    wave: 1,
    severity: "high",
    title: "Weak Password Policy",
    excerpt: "Passwords accept any 6+ character string without requiring uppercase, numbers, or special characters.",
    content: `## Weak Password Policy\n\n### Severity: High\n### Wave: 1\n\nPasswords accept any 6+ character string without requiring uppercase, numbers, or special characters.\n\n### Current Policy\n- Minimum length: 6 characters\n- No complexity requirements\n\n### NIST Guidelines Violation\nCurrent policy contradicts NIST 800-63B guidelines:\n- Should allow up to 64+ characters\n- Should NOT require complexity rules\n- Should check against known breaches\n\n### Recommendation\n\`\`\`javascript\n// Better policy\nminLength: 8,\nmaxLength: 64,\ncheckBreaches: true\n\`\`\``,
    timestamp: "2026-02-12T11:15:00Z",
    tags: ["authentication", "passwords", "nist"],
  },
  {
    id: "f12",
    agentName: "A11yAudit",
    agentId: "a11y-001",
    domain: "Accessibility",
    wave: 3,
    severity: "medium",
    title: "Insufficient Color Contrast in Error States",
    excerpt: "Error text uses #ef4444 on #1f2937 backgrounds, giving a contrast ratio of 3.8:1 (WCAG AA requires 4.5:1).",
    content: `## Insufficient Color Contrast in Error States\n\n### Severity: Medium\n### Wave: 3\n\nError text uses #ef4444 on #1f2937 backgrounds, giving a contrast ratio of 3.8:1 (WCAG AA requires 4.5:1).\n\n### WCAG Violations\n- WCAG 1.4.3: Contrast (Minimum) - Level AA\n\n### Affected Elements\n- Error messages\n- Validation feedback\n- Alert banners\n\n### Recommendation\nUse lighter red or add text shadow:\n\`\`\`css\n.error-text {\n  color: #f87171; /* 4.7:1 contrast */\n}\n\`\`\``,
    timestamp: "2026-02-21T10:00:00Z",
    tags: ["accessibility", "contrast", "wcag"],
  },
  {
    id: "f13",
    agentName: "UXAnalyzer",
    agentId: "ux-001",
    domain: "User Experience",
    wave: 1,
    severity: "high",
    title: "Missing Loading States for Async Operations",
    excerpt: "No loading indicators shown during API calls, causing users to wonder if their actions were registered.",
    content: `## Missing Loading States for Async Operations\n\n### Severity: High\n### Wave: 1\n\nNo loading indicators shown during API calls, causing users to wonder if their actions were registered.\n\n### User Reports\n- "Click save but nothing happens"\n- "How do I know it's working?"\n- "I keep clicking multiple times"\n\n### Affected Actions\n- Form submissions\n- Search queries\n- Data exports\n- Profile updates\n\n### Recommendation\nAdd loading spinners or skeleton screens for all async operations.`,
    timestamp: "2026-02-11T14:20:00Z",
    tags: ["loading", "feedback", "ux"],
  },
  {
    id: "f14",
    agentName: "PerformancePro",
    agentId: "perf-001",
    domain: "Performance",
    wave: 1,
    severity: "medium",
    title: "Blocking JavaScript in Head",
    excerpt: "Non-critical JavaScript loaded in <head> blocks page render by 1.2 seconds.",
    content: `## Blocking JavaScript in Head\n\n### Severity: Medium\n### Wave: 1\n\nNon-critical JavaScript loaded in <head> blocks page render by 1.2 seconds.\n\n### Impact\n- First Contentful Paint: 2.8s\n- Time to Interactive: 4.1s\n\n### Solution\nMove non-critical scripts to end of <body> or use \`defer\`:\n\`\`\`html\n<script src="analytics.js" defer></script>\n\`\`\``,
    timestamp: "2026-02-10T16:00:00Z",
    tags: ["render-blocking", "javascript", "fcp"],
  },
  {
    id: "f15",
    agentName: "SecurityScanner",
    agentId: "sec-001",
    domain: "API Security",
    wave: 2,
    severity: "high",
    title: "Missing Rate Limiting on Auth Endpoints",
    excerpt: "Login and password reset endpoints have no rate limiting, vulnerable to brute force attacks.",
    content: `## Missing Rate Limiting on Auth Endpoints\n\n### Severity: High\n### Wave: 2\n\nLogin and password reset endpoints have no rate limiting, vulnerable to brute force attacks.\n\n### Attack Scenario\n\`\`\`\nPOST /api/auth/login\nAttempt rate: 1000/minute\nNo blocking observed\n\`\`\`\n\n### Recommendation\nImplement rate limiting:\n- Login: 5 attempts per minute per IP\n- Password reset: 3 per hour per email\n- Add CAPTCHA after failed attempts`,
    timestamp: "2026-02-17T12:30:00Z",
    tags: ["rate-limiting", "brute-force", "authentication"],
  },
  {
    id: "f16",
    agentName: "A11yAudit",
    agentId: "a11y-001",
    domain: "Accessibility",
    wave: 1,
    severity: "low",
    title: "Focus Order Not Logical",
    excerpt: "Tab order skips the search input and goes straight to navigation, confusing keyboard users.",
    content: `## Focus Order Not Logical\n\n### Severity: Low\n### Wave: 1\n\nTab order skips the search input and goes straight to navigation, confusing keyboard users.\n\n### Current Order\n1. Logo\n2. Menu\n3. Skip to content\n4. (jumps to footer)\n\n### Expected Order\n1. Logo\n2. Search\n3. Menu\n4. Main content\n\n### Recommendation\nReview DOM order matches visual tab order.`,
    timestamp: "2026-02-12T08:00:00Z",
    tags: ["keyboard", "focus", "navigation"],
  },
  {
    id: "f17",
    agentName: "UXAnalyzer",
    agentId: "ux-001",
    domain: "User Experience",
    wave: 2,
    severity: "medium",
    title: "Date Picker Inconsistent with System Locale",
    excerpt: "Date picker always uses MM/DD/YYYY format regardless of user's locale settings.",
    content: `## Date Picker Inconsistent with System Locale\n\n### Severity: Medium\n### Wave: 2\n\nDate picker always uses MM/DD/YYYY format regardless of user's locale settings.\n\n### User Impact\n- International users confused by date format\n- Potential data entry errors\n- Perceived as "American-only" product\n\n### Solution\n\`\`\`javascript\n// Use Intl.DateTimeFormat\nnew Intl.DateTimeFormat(navigator.language).format(date)\n\`\`\``,
    timestamp: "2026-02-16T11:45:00Z",
    tags: ["localization", "i18n", "dates"],
  },
  {
    id: "f18",
    agentName: "PerformancePro",
    agentId: "perf-001",
    domain: "Performance",
    wave: 2,
    severity: "low",
    title: "Unused CSS in Production Bundle",
    excerpt: "Build includes 340KB of unused CSS from disabled features and old components.",
    content: `## Unused CSS in Production Bundle\n\n### Severity: Low\n### Wave: 2\n\nBuild includes 340KB of unused CSS from disabled features and old components.\n\n### Tools\n- PurgeCSS can remove unused styles\n- Tree-shaking for CSS modules\n\n### Savings\n- 340KB CSS removed\n- 120KB bundle size reduction`,
    timestamp: "2026-02-15T07:30:00Z",
    tags: ["bundle-size", "css", "optimization"],
  },
  {
    id: "f19",
    agentName: "SecurityScanner",
    agentId: "sec-001",
    domain: "Data Protection",
    wave: 3,
    severity: "high",
    title: "Session Tokens Not Invalidated on Password Change",
    excerpt: "When users change their password, existing sessions remain active, allowing continued access from compromised devices.",
    content: `## Session Tokens Not Invalidated on Password Change\n\n### Severity: High\n### Wave: 3\n\nWhen users change their password, existing sessions remain active, allowing continued access from compromised devices.\n\n### Security Impact\n- Compromised sessions persist after password reset\n- Cannot force logout from stolen devices\n- Violates OWASP recommendations\n\n### Recommendation\n\`\`\`javascript\n// On password change\nawait invalidateAllSessions(userId);\n// Except current session\nawait invalidateOtherSessions(userId, currentSessionId);\n\`\`\``,
    timestamp: "2026-02-20T09:15:00Z",
    tags: ["sessions", "authentication", "security"],
  },
  {
    id: "f20",
    agentName: "UXAnalyzer",
    agentId: "ux-001",
    domain: "User Experience",
    wave: 3,
    severity: "low",
    title: "Tooltip Truncates Long Text",
    excerpt: "Tooltips cut off text longer than 150 characters instead of wrapping or expanding.",
    content: `## Tooltip Truncates Long Text\n\n### Severity: Low\n### Wave: 3\n\nTooltips cut off text longer than 150 characters instead of wrapping or expanding.\n\n### Example\n"This feature allows you to export your data in multiple formats including..." → truncated\n\n### Solution\n\`\`\`css\n.tooltip {\n  max-width: 300px;\n  white-space: normal;\n  word-wrap: break-word;\n}\n\`\`\``,
    timestamp: "2026-02-21T14:45:00Z",
    tags: ["tooltips", "ui", "text-overflow"],
  },
];
