import React, { useState } from "react";
import { ScrollText } from "lucide-react";
import { cn } from "../lib/utils";
import { ContextualEmptyState } from "../components/ui/ContextualEmptyState";

type Category = "security" | "privacy" | "compliance" | "access" | "data-retention" | "model-usage";
type Status = "active" | "draft" | "deprecated";

interface Policy {
  id: string;
  name: string;
  category: Category;
  status: Status;
  version: string;
  lastUpdated: string;
  author: string;
  description: string;
  rules: string[];
  violations: number;
  affectedAgents: string[];
}

interface Violation {
  agent: string;
  description: string;
  timestamp: string;
}

const CATEGORY_COLORS: Record<Category, { text: string; bg: string; border: string }> = {
  security: { text: "text-rose-400", bg: "bg-rose-500/15", border: "border-rose-500/30" },
  privacy: { text: "text-purple-400", bg: "bg-purple-500/15", border: "border-purple-500/30" },
  compliance: { text: "text-primary", bg: "bg-primary/15", border: "border-primary/30" },
  access: { text: "text-blue-400", bg: "bg-blue-500/15", border: "border-blue-500/30" },
  "data-retention": { text: "text-amber-400", bg: "bg-amber-500/15", border: "border-amber-500/30" },
  "model-usage": { text: "text-emerald-400", bg: "bg-emerald-500/15", border: "border-emerald-500/30" },
};

const CATEGORY_LABELS: Record<Category, string> = {
  security: "Security",
  privacy: "Privacy",
  compliance: "Compliance",
  access: "Access",
  "data-retention": "Data Retention",
  "model-usage": "Model Usage",
};

const STATUS_STYLES: Record<Status, string> = {
  active: "text-emerald-400 bg-emerald-500/15 border-emerald-500/30",
  draft: "text-amber-400 bg-amber-500/15 border-amber-500/30",
  deprecated: "text-[var(--color-text-muted)] bg-[var(--color-surface-3)]/40 border-[var(--color-surface-3)]/30",
};

const POLICIES: Policy[] = [
  {
    id: "pol-001", name: "Agent Data Access Control", category: "security", status: "active",
    version: "2.3.1", lastUpdated: "2026-02-18", author: "Xavier Chen",
    description: "Defines mandatory access control boundaries for all autonomous agents interacting with production data stores. Ensures agents operate within least-privilege principles and cannot escalate their own permissions.",
    rules: ["Agents must request scoped tokens for each data access session", "No agent may access PII without explicit user consent flow", "All data access must be logged with agent ID and session context"],
    violations: 3, affectedAgents: ["Atlas", "Beacon", "Cortex", "Delta"],
  },
  {
    id: "pol-002", name: "PII Handling Standard", category: "privacy", status: "active",
    version: "1.8.0", lastUpdated: "2026-02-15", author: "Mira Patel",
    description: "Establishes organization-wide standards for how personally identifiable information is collected, processed, stored, and deleted across all agent workflows.",
    rules: ["PII must be encrypted at rest and in transit", "Retention of PII data must not exceed 90 days without renewal", "Agents must redact PII from logs and debug output", "User deletion requests must propagate within 24 hours"],
    violations: 1, affectedAgents: ["Cortex", "Echo", "Forge"],
  },
  {
    id: "pol-003", name: "SOC 2 Compliance Framework", category: "compliance", status: "active",
    version: "3.0.0", lastUpdated: "2026-02-10", author: "Jordan Blake",
    description: "Maintains alignment with SOC 2 Type II audit requirements across all automated and agent-driven systems. Covers availability, security, processing integrity, confidentiality, and privacy.",
    rules: ["Quarterly access reviews must be completed for all agent roles", "Incident response procedures must be tested monthly", "Change management requires approval from two authorized reviewers"],
    violations: 0, affectedAgents: ["Atlas", "Beacon", "Cortex", "Delta", "Echo"],
  },
  {
    id: "pol-004", name: "Role-Based Agent Permissions", category: "access", status: "active",
    version: "1.5.2", lastUpdated: "2026-02-12", author: "Xavier Chen",
    description: "Defines the role-based access control matrix for agent capabilities, ensuring agents can only perform actions aligned with their designated operational role.",
    rules: ["Each agent must be assigned exactly one primary role", "Cross-role actions require explicit delegation tokens", "Admin-level capabilities are restricted to supervisor agents only"],
    violations: 2, affectedAgents: ["Atlas", "Forge", "Gamma"],
  },
  {
    id: "pol-005", name: "Log Retention Policy", category: "data-retention", status: "active",
    version: "2.1.0", lastUpdated: "2026-01-28", author: "Sam Torres",
    description: "Governs the lifecycle of operational logs, audit trails, and telemetry data generated by agents and platform services.",
    rules: ["Operational logs retained for 30 days in hot storage", "Audit logs must be retained for 1 year minimum", "Telemetry data older than 7 days moves to cold storage", "Log deletion requires compliance team sign-off"],
    violations: 0, affectedAgents: ["Beacon", "Delta", "Echo"],
  },
  {
    id: "pol-006", name: "LLM Output Safety", category: "model-usage", status: "active",
    version: "1.2.0", lastUpdated: "2026-02-20", author: "Mira Patel",
    description: "Ensures all LLM-generated outputs are validated, filtered, and audited before being surfaced to end users or consumed by downstream systems.",
    rules: ["All model outputs must pass content safety filters", "Agents must not execute model-generated code without sandbox validation", "Hallucination detection must be enabled for user-facing responses"],
    violations: 5, affectedAgents: ["Cortex", "Echo", "Forge", "Gamma", "Atlas"],
  },
  {
    id: "pol-007", name: "API Key Rotation Standard", category: "security", status: "active",
    version: "1.0.3", lastUpdated: "2026-02-05", author: "Jordan Blake",
    description: "Mandates regular rotation of API keys and service credentials used by agents, reducing the window of exposure from compromised credentials.",
    rules: ["API keys must be rotated every 30 days", "Expired keys must be revoked within 1 hour of rotation", "Key rotation events must be logged and auditable"],
    violations: 1, affectedAgents: ["Atlas", "Beacon", "Delta"],
  },
  {
    id: "pol-008", name: "Consent Management Framework", category: "privacy", status: "draft",
    version: "0.9.0", lastUpdated: "2026-02-19", author: "Sam Torres",
    description: "Draft framework for managing user consent preferences across agent interactions, ensuring opt-in/opt-out signals are respected in all data processing pipelines.",
    rules: ["Consent status must be checked before every data collection action", "Users must be able to revoke consent at any time with immediate effect"],
    violations: 0, affectedAgents: ["Cortex", "Echo"],
  },
  {
    id: "pol-009", name: "Legacy Agent Sunset Protocol", category: "access", status: "deprecated",
    version: "1.0.0", lastUpdated: "2025-12-01", author: "Xavier Chen",
    description: "Previously governed the decommissioning process for legacy agents. Superseded by the updated Agent Lifecycle Management policy.",
    rules: ["Deprecated agents must have capabilities revoked within 7 days", "All sessions for deprecated agents must be terminated"],
    violations: 0, affectedAgents: ["LegacyBot-v1"],
  },
  {
    id: "pol-010", name: "Model Fine-Tuning Governance", category: "model-usage", status: "draft",
    version: "0.5.0", lastUpdated: "2026-02-21", author: "Mira Patel",
    description: "Draft governance framework for fine-tuning foundation models with organizational data. Covers data selection, training pipeline security, and model versioning.",
    rules: ["Training data must be reviewed for bias before fine-tuning", "Fine-tuned models must pass safety eval before deployment", "All training runs must be versioned and reproducible", "Data provenance must be documented for each training dataset"],
    violations: 0, affectedAgents: ["Cortex", "Forge"],
  },
];

const SAMPLE_VIOLATIONS: Record<string, Violation[]> = {
  "pol-001": [
    { agent: "Beacon", description: "Accessed user table without scoped token", timestamp: "2026-02-17 14:32" },
    { agent: "Cortex", description: "Attempted permission escalation via chained requests", timestamp: "2026-02-16 09:11" },
    { agent: "Atlas", description: "Logged PII in debug output without redaction", timestamp: "2026-02-14 22:05" },
  ],
  "pol-002": [
    { agent: "Echo", description: "PII detected in plaintext log entry", timestamp: "2026-02-13 11:47" },
  ],
  "pol-004": [
    { agent: "Forge", description: "Executed admin-level action without delegation token", timestamp: "2026-02-11 16:20" },
    { agent: "Gamma", description: "Cross-role data query without authorization", timestamp: "2026-02-09 08:33" },
  ],
  "pol-006": [
    { agent: "Cortex", description: "Unfiltered model output served to user", timestamp: "2026-02-20 10:15" },
    { agent: "Forge", description: "Executed model-generated code outside sandbox", timestamp: "2026-02-19 15:42" },
    { agent: "Echo", description: "Hallucinated citation in user-facing response", timestamp: "2026-02-18 13:08" },
  ],
  "pol-007": [
    { agent: "Delta", description: "API key exceeded 30-day rotation window", timestamp: "2026-02-04 07:55" },
  ],
};

const ALL_CATEGORIES: Category[] = ["security", "privacy", "compliance", "access", "data-retention", "model-usage"];

function complianceForCategory(category: Category): number {
  const catPolicies = POLICIES.filter((p) => p.category === category && p.status === "active");
  if (catPolicies.length === 0) {return 100;}
  const totalViolations = catPolicies.reduce((sum, p) => sum + p.violations, 0);
  const maxExpected = catPolicies.length * 5;
  return Math.max(0, Math.round(100 - (totalViolations / maxExpected) * 100));
}

export default function PolicyManager() {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [activeCategory, setActiveCategory] = useState<Category | null>(null);

  const filtered = activeCategory ? POLICIES.filter((p) => p.category === activeCategory) : POLICIES;
  const selected = selectedId ? POLICIES.find((p) => p.id === selectedId) ?? null : null;

  const totalPolicies = POLICIES.length;
  const activePolicies = POLICIES.filter((p) => p.status === "active").length;
  const totalViolations = POLICIES.reduce((sum, p) => sum + p.violations, 0);

  return (
    <div className="min-h-screen bg-[var(--color-surface-0)] text-[var(--color-text-primary)] p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <h1 className="text-2xl font-bold tracking-tight">Policy Manager</h1>
        <button className="bg-primary hover:bg-primary text-[var(--color-text-primary)] px-4 py-2 rounded text-sm font-medium transition-colors">
          + New Policy
        </button>
      </div>

      {/* Category Filter Chips */}
      <div className="flex items-center gap-2 flex-wrap">
        <button
          onClick={() => setActiveCategory(null)}
          className={cn(
            "px-3 py-1 rounded-full text-sm border transition-colors",
            activeCategory === null
              ? "bg-primary border-primary text-[var(--color-text-primary)]"
              : "bg-[var(--color-surface-1)] border-[var(--color-border)] text-[var(--color-text-secondary)] hover:border-[var(--color-surface-3)]"
          )}
        >
          All
        </button>
        {ALL_CATEGORIES.map((cat) => {
          const colors = CATEGORY_COLORS[cat];
          const isActive = activeCategory === cat;
          return (
            <button
              key={cat}
              onClick={() => setActiveCategory(isActive ? null : cat)}
              className={cn(
                "px-3 py-1 rounded-full text-sm border transition-colors",
                isActive
                  ? cn(colors.bg, colors.border, colors.text)
                  : "bg-[var(--color-surface-1)] border-[var(--color-border)] text-[var(--color-text-secondary)] hover:border-[var(--color-surface-3)]"
              )}
            >
              {CATEGORY_LABELS[cat]}
            </button>
          );
        })}
      </div>

      {/* Stats Bar */}
      <div className="grid grid-cols-4 gap-4">
        {[
          { label: "Total Policies", value: totalPolicies, style: "text-[var(--color-text-primary)]" },
          { label: "Active", value: activePolicies, style: "text-emerald-400" },
          { label: "Violations This Month", value: totalViolations, style: totalViolations > 0 ? "text-rose-400" : "text-emerald-400" },
          { label: "Last Audit", value: "Feb 10, 2026", style: "text-[var(--color-text-secondary)]" },
        ].map((stat) => (
          <div key={stat.label} className="bg-[var(--color-surface-1)] border border-[var(--color-border)] rounded-lg p-4">
            <div className="text-[var(--color-text-muted)] text-xs uppercase tracking-wider mb-1">{stat.label}</div>
            <div className={cn("text-xl font-semibold", stat.style)}>{stat.value}</div>
          </div>
        ))}
      </div>

      {/* Two-Column Layout */}
      <div className="grid grid-cols-2 gap-6 min-h-[480px]">
        {/* Left: Policy List */}
        <div className="space-y-2 overflow-y-auto max-h-[520px] pr-1">
          {filtered.map((policy) => {
            const catColors = CATEGORY_COLORS[policy.category];
            const isSelected = selectedId === policy.id;
            return (
              <button
                key={policy.id}
                onClick={() => setSelectedId(isSelected ? null : policy.id)}
                className={cn(
                  "w-full text-left bg-[var(--color-surface-1)] border rounded-lg p-4 transition-colors",
                  isSelected ? "border-primary ring-1 ring-indigo-500/30" : "border-[var(--color-border)] hover:border-[var(--color-border)]"
                )}
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1 min-w-0">
                    <div className="font-medium text-[var(--color-text-primary)] truncate">{policy.name}</div>
                    <div className="flex items-center gap-2 mt-2 flex-wrap">
                      <span className={cn("text-xs px-2 py-0.5 rounded-full border", catColors.bg, catColors.border, catColors.text)}>
                        {CATEGORY_LABELS[policy.category]}
                      </span>
                      <span className={cn("text-xs px-2 py-0.5 rounded-full border", STATUS_STYLES[policy.status])}>
                        {policy.status}
                      </span>
                      <span className="text-xs text-[var(--color-text-muted)]">v{policy.version}</span>
                    </div>
                  </div>
                  <div className="text-right shrink-0">
                    {policy.violations > 0 ? (
                      <div className="text-rose-400 font-semibold text-sm">{policy.violations} violation{policy.violations !== 1 ? "s" : ""}</div>
                    ) : (
                      <div className="text-[var(--color-text-muted)] text-sm">0 violations</div>
                    )}
                    <div className="text-[var(--color-text-muted)] text-xs mt-1">{policy.lastUpdated}</div>
                  </div>
                </div>
              </button>
            );
          })}
          {filtered.length === 0 && (
            <ContextualEmptyState
              icon={ScrollText}
              title="No policies here yet"
              description="Add your first policy to define governance rules for your team."
              size="sm"
            />
          )}
        </div>

        {/* Right: Detail Panel */}
        <div className="bg-[var(--color-surface-1)] border border-[var(--color-border)] rounded-lg p-6 overflow-y-auto max-h-[520px]">
          {selected ? (
            <div className="space-y-5">
              {/* Detail Header */}
              <div>
                <h2 className="text-xl font-semibold text-[var(--color-text-primary)]">{selected.name}</h2>
                <div className="flex items-center gap-2 mt-2 flex-wrap">
                  <span className={cn("text-xs px-2 py-0.5 rounded-full border", CATEGORY_COLORS[selected.category].bg, CATEGORY_COLORS[selected.category].border, CATEGORY_COLORS[selected.category].text)}>
                    {CATEGORY_LABELS[selected.category]}
                  </span>
                  <span className={cn("text-xs px-2 py-0.5 rounded-full border", STATUS_STYLES[selected.status])}>
                    {selected.status}
                  </span>
                </div>
              </div>

              {/* Metadata */}
              <div className="grid grid-cols-3 gap-3">
                {[
                  { label: "Version", value: `v${selected.version}` },
                  { label: "Author", value: selected.author },
                  { label: "Last Updated", value: selected.lastUpdated },
                ].map((item) => (
                  <div key={item.label}>
                    <div className="text-[var(--color-text-muted)] text-xs uppercase tracking-wider">{item.label}</div>
                    <div className="text-[var(--color-text-primary)] text-sm mt-0.5">{item.value}</div>
                  </div>
                ))}
              </div>

              {/* Description */}
              <div>
                <div className="text-[var(--color-text-muted)] text-xs uppercase tracking-wider mb-1">Description</div>
                <p className="text-[var(--color-text-secondary)] text-sm leading-relaxed">{selected.description}</p>
              </div>

              {/* Rules */}
              <div>
                <div className="text-[var(--color-text-muted)] text-xs uppercase tracking-wider mb-2">Rules</div>
                <ol className="space-y-1.5">
                  {selected.rules.map((rule, i) => (
                    <li key={i} className="flex gap-2 text-sm">
                      <span className="text-primary font-mono shrink-0">{i + 1}.</span>
                      <span className="text-[var(--color-text-primary)]">{rule}</span>
                    </li>
                  ))}
                </ol>
              </div>

              {/* Affected Agents */}
              <div>
                <div className="text-[var(--color-text-muted)] text-xs uppercase tracking-wider mb-2">Affected Agents</div>
                <div className="flex flex-wrap gap-1.5">
                  {selected.affectedAgents.map((agent) => (
                    <span key={agent} className="bg-[var(--color-surface-2)] border border-[var(--color-border)] text-[var(--color-text-primary)] text-xs px-2 py-0.5 rounded">
                      {agent}
                    </span>
                  ))}
                </div>
              </div>

              {/* Violations Table */}
              <div>
                <div className="text-[var(--color-text-muted)] text-xs uppercase tracking-wider mb-2">
                  Recent Violations
                </div>
                {(SAMPLE_VIOLATIONS[selected.id]?.length ?? 0) > 0 ? (
                  <div className="border border-[var(--color-border)] rounded overflow-hidden">
                    <div className="grid grid-cols-[100px_1fr_130px] gap-px bg-[var(--color-surface-2)] text-xs">
                      <div className="bg-[var(--color-surface-1)] px-3 py-2 text-[var(--color-text-muted)] font-medium">Agent</div>
                      <div className="bg-[var(--color-surface-1)] px-3 py-2 text-[var(--color-text-muted)] font-medium">Description</div>
                      <div className="bg-[var(--color-surface-1)] px-3 py-2 text-[var(--color-text-muted)] font-medium">Timestamp</div>
                    </div>
                    {(SAMPLE_VIOLATIONS[selected.id] ?? []).slice(0, 3).map((v, i) => (
                      <div key={i} className="grid grid-cols-[100px_1fr_130px] gap-px bg-[var(--color-surface-2)] text-xs">
                        <div className="bg-[var(--color-surface-1)] px-3 py-2 text-rose-400">{v.agent}</div>
                        <div className="bg-[var(--color-surface-1)] px-3 py-2 text-[var(--color-text-secondary)]">{v.description}</div>
                        <div className="bg-[var(--color-surface-1)] px-3 py-2 text-[var(--color-text-muted)]">{v.timestamp}</div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-[var(--color-text-muted)] text-sm bg-[var(--color-surface-2)]/50 rounded px-3 py-3 text-center">No violations this month</div>
                )}
              </div>

              {/* Action Buttons */}
              <div className="flex gap-2 pt-2">
                <button className="bg-primary hover:bg-primary text-[var(--color-text-primary)] px-3 py-1.5 rounded text-sm transition-colors">
                  Edit Policy
                </button>
                <button className="bg-[var(--color-surface-2)] hover:bg-[var(--color-surface-3)] text-amber-400 border border-[var(--color-border)] px-3 py-1.5 rounded text-sm transition-colors">
                  Deprecate
                </button>
                <button className="bg-[var(--color-surface-2)] hover:bg-[var(--color-surface-3)] text-[var(--color-text-primary)] border border-[var(--color-border)] px-3 py-1.5 rounded text-sm transition-colors">
                  Run Audit
                </button>
              </div>
            </div>
          ) : (
            <div className="flex items-center justify-center h-full text-[var(--color-text-muted)] text-sm">
              Select a policy to view details
            </div>
          )}
        </div>
      </div>

      {/* Compliance Score */}
      <div className="bg-[var(--color-surface-1)] border border-[var(--color-border)] rounded-lg p-5">
        <h3 className="text-sm font-medium text-[var(--color-text-secondary)] uppercase tracking-wider mb-4">Compliance Score by Category</h3>
        <div className="space-y-3">
          {ALL_CATEGORIES.map((cat) => {
            const score = complianceForCategory(cat);
            const colors = CATEGORY_COLORS[cat];
            return (
              <div key={cat} className="flex items-center gap-3">
                <div className="w-28 text-sm text-[var(--color-text-secondary)] shrink-0">{CATEGORY_LABELS[cat]}</div>
                <div className="flex-1 bg-[var(--color-surface-2)] rounded-full h-3 overflow-hidden">
                  <div
                    className={cn("h-full rounded-full transition-all", colors.bg.replace("/15", ""))}
                    style={{ width: `${score}%` }}
                  />
                </div>
                <div className={cn("w-10 text-right text-sm font-medium", score >= 90 ? "text-emerald-400" : score >= 70 ? "text-amber-400" : "text-rose-400")}>
                  {score}%
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
